### ISSUE TITLE
Cannot depickle SQL-based Translator on SQLAlchemy>=2

### ISSUE THREAD

**Issue by rsundqvist** [rsundqvist/id-translation#37]
```python
Traceback (most recent call last):
  File "/home/dev/git/id-translation/src/id_translation/_translator.py", line 581, in restore
    ans = pickle.load(f)  # noqa: S301
          ^^^^^^^^^^^^^^
  File "/home/dev/git/id-translation/.venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 1636, in __new__
    raise TypeError(
TypeError: Can't replace canonical symbol for unpickled with new int value -4533261097786850201
```
Works for `sqlalchemy<2`.

**Comment by rsundqvist** [comment]
https://github.com/sqlalchemy/sqlalchemy/issues/9423
